### ISSUE TITLE
error starting localserver.js 

### ISSUE THREAD

**Issue by cortezthekiller** [googlecreativelab/coder#112]
Hi, I've installed node.js in an ARM Chromebook running Ubuntu 14.04 Crouton chroot. I've installed node.js v7.2.1
I've cloned coder from github but when I try to start the localserver I get the following error:

    `/home/rodrigo/tmp/coder/coder-base/node_modules/socket.io/lib/store.js:35
     Store.prototype.__proto__ = EventEmitter.prototype;
                                        ^                                         
    TypeError: Cannot read property 'prototype' of undefined
        at Object.<anonymous> (/home/rodrigo/tmp/coder/coder-base/node_modules/socket.io/lib/store.js:35:41)
        at Module._compile (module.js:571:32)
        at Object.Module._extensions..js (module.js:580:10)
        at Module.load (module.js:488:32)
        at tryModuleLoad (module.js:447:12)
        at Function.Module._load (module.js:439:3)
        at Module.require (module.js:498:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (/home/rodrigo/tmp/coder/coder-base/node_modules/socket.io/lib/manager.js:16:13)
        at Module._compile (module.js:571:32)

I'm not familiar with JavaScript prototypes. What could be wrong here? I've not touched the code, I'm just using the last version from GitHub

**Comment by cortezthekiller** [comment]
Solved as per [https://github.com/LearnBoost/websocket.io/issues/55](https://github.com/LearnBoost/websocket.io/issues/55) 
process.EventEmitter is deprecated. use require('events') instead
